name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "dvc[s3]" pandas  # DVC with S3 support and pandas

      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region eu-north-1 

      - name: Configure DVC Remote
        run: |
          # Add the DVC remote if not already present
          if ! dvc remote list | grep -q '^myremote\s'; then
            dvc remote add -d myremote s3://omgbucket08
          fi
          # Modify the DVC remote with AWS credentials and region
          dvc remote modify myremote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify myremote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc remote modify myremote region eu-north-1  # Replace with your region

      - name: Verify DVC Remote Configuration
        run: |
          dvc remote list

      - name: Pull data from remote
        run: |
          dvc pull

      - name: Reproduce DVC pipeline
        run: |
          dvc repro

      - name: Push results to remote
        run: |
          dvc push

